#name: Test pulling secrets
#run-name: Test pulling secrets
#on: [ push ]
#jobs:
#  pull-secret-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Retrieve secret
#        env:
#          super_secret: ${{ secrets.SUPERSECRET }}
#        run: echo $super_secret
