## https://github.com/actions
#name: restfully-call-poke-api
#run-name: RESTfully call Poke API
#on: [push]
#jobs:
#  run-poke-api-test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4 # checkout repo this is part of, now you can run scripts in it
#      - uses: actions/setup-node@v4 # install specified version of node
#        with:
#          node-version: '20'
#      - run: npm install
#      - run: npm run poke_api_test
