name: Print repository metadata
run-name: Print run name
on: [push]

jobs:
  print_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Execute Node Script
        run: node printRepositoryMetadata.js
